import Head from "next/head";
import styled from "styled-components";
import { align_center } from "../styles/mixins";
import Image from "next/image";
import stars from "../public/stars.svg";
import starsJpg from "../public/stars.jpg";

// wrapper for scrolling
const ParallaxWrapper = styled.div`
  height: 100vh;
  overflow-x: hidden;
  overflow-y: auto;
  perspective: 300px;
`;

const ParallaxGroup = styled.div`
  position: relative;
  height: 100vh;
  transform-style: preserve-3d;
  border: 1px solid red;
`;
const IntroScreen = styled(ParallaxGroup)`
  height: 100vh;
  background-image: linear-gradient(white 90%, transparent);
  ${align_center}
  z-index: 5;
`;
const OutroScreen = styled(ParallaxGroup)`
  height: 100vh;
  background-color: white;

  ${align_center}
`;

const Group1 = styled(ParallaxGroup)`
  > div:first-child {
    /* background-image: linear-gradient(transparent, red, transparent); */
  }
`;
const Group2 = styled(ParallaxGroup)`
  > div:first-child {
    background-image: linear-gradient(transparent, white 5%);
  }
`;

const ParallaxLayer = styled.div`
  position: absolute;
  inset: 0;
  ${align_center}
`;

const BaseLayer = styled(ParallaxLayer)`
  transform: translateZ(-300px) scale(3);
`;
const MidLayer = styled(ParallaxLayer)`
  transform: translateZ(0);
  display: flex;
  flex-direction: column;
`;
const TopLayer = styled(ParallaxLayer)`
  transform: translateZ(200px);
`;

const StyledP = styled.p`
  background-color: white;
`;

export default function AllWhite() {
  return (
    <>
      <Head>
        <title>Parallax Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParallaxWrapper>
        <IntroScreen> Intro Screen</IntroScreen>
        <Group1>
          <BaseLayer>
            <Image src={starsJpg.src} fill={true} />
          </BaseLayer>
          <MidLayer>
            <StyledP>A long long time ago,</StyledP>
            <StyledP>in a galaxy far far away...</StyledP>
          </MidLayer>
        </Group1>
        <Group2>
          <MidLayer>Mid Layer</MidLayer>
          <TopLayer>Top Layer</TopLayer>
        </Group2>
        <OutroScreen>Outro Screen</OutroScreen>
      </ParallaxWrapper>
    </>
  );
}
