import React from "react";
import Head from "next/head";
import styled from "styled-components";
import { align_center } from "../styles/mixins";

const StyledInfo = styled.div`
  position: fixed;
  top: 0;
  width: 100vw;
  background-color: white;
`;

const Container = styled.div`
  width: 100vw;
  height: 100vh;
  scroll-snap-type: x mandatory;
  overflow-x: scroll;
  overflow-y: hidden;
  scroll-snap-points-x: repeat(100vw);
  display: flex;
  flex-direction: row;
`;
const Section = styled.section`
  ${align_center}
  width: 100vw;
  height: 100vh;
  font-size: 10em;
  scroll-snap-align: start;
  flex: none;

  &:nth-of-type(1) {
    background-color: yellow;
    color: darkgoldenrod;
  }
  &:nth-of-type(2) {
    background-color: teal;
    color: navy;
  }
  &:nth-of-type(3) {
    background-color: lime;
    color: darkgreen;
  }
`;

export default function HorizontalScroll() {
  return (
    <>
      <Head>
        <title>Horizontal Scroll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledInfo>Hold shift to scroll horizontally</StyledInfo>
      <Container>
        <Section>
          <h1>Page one</h1>
        </Section>
        <Section>
          <h1>Page two</h1>
        </Section>
        <Section>
          <h1>Page three</h1>
        </Section>
      </Container>
    </>
  );
}
