import Head from "next/head";
import styled from "styled-components";

const Parallax = styled.div`
  height: 100vh;
  overflow-x: hidden;
  overflow-y: auto;
  perspective: 1px;
  margin: 0;
`;

const ParallaxLayer = styled.div`
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
`;

const Layer1 = styled(ParallaxLayer)`
  transform: translateZ(0);
  background-color: red;
  width: 100%;
  height: 100em;
`;

const Layer2 = styled(ParallaxLayer)`
  transform: translateZ(-1px);
  background-color: green;
  height: 50em;
  top: 10em;
  width: 100%;
`;
// decreasing the value of translateZ will push element further away
const Layer3 = styled(ParallaxLayer)`
  transform: translateZ(-2px);
  background-color: blue;
  height: 50em;
  width: 100%;
  top: 20em;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Parallax Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Parallax>
        <Layer1>layer 1</Layer1>
        <Layer2>layer 2</Layer2>
        <Layer3>layer 3</Layer3>
      </Parallax>
      <Parallax>
        <Layer1>layer 1</Layer1>
        <Layer2>layer 2</Layer2>
        <Layer3>layer 3</Layer3>
      </Parallax>
    </>
  );
}
